### ISSUE TITLE
Restrict Delete Item functionality

### ISSUE THREAD

**Issue by facundoj** [how-to-node/retro-tool#10]
Any guest can delete items. We need to restrict this functionality to item's autor only.

**Comment by gsas2** [comment]
Item's author or Retro admin, right?

**Comment by facundoj** [comment]
Nope. Retro Owner is the creator of the Retro, and he can:
- Update Retro's status (feature pending)

Item's Author is another concept; the one who added the item. He can:
- Delete the Item (this bug)
- Modify the Item (feature pending)

[Here](https://github.com/how-to-node/retro-tool/blob/master/src/static/model/retros/retro.js#LC50) is the model object:

``` js
var newItem = {
    author: author,
    description: description,
    sign: sign
};
```

**Comment by facundoj** [comment]
Fix https://github.com/how-to-node/retro-tool/pull/9
